import type { MenuToggles, MenuOrder, MenuLabels } from "./types";

export const defaultMenuToggles: MenuToggles = {
  main: {
    dashboard: true,
    complexes: true,
    buildings: true,
    members: true,
    users: true,
    approvals: true,
    "parking.qrs": true,
    "parking.scans": true,
    "meter.cycles": true,
    "meter.submissions": true,
    notices: true,
    settings: true,
    mypage: true,
    notifications: true,
  },
  guard: {
    scan: true,
    history: true,
    notices: true,
    mypage: true,
    notifications: false,
  },
  resident: {
    scan: true,
    myQr: true,
    alerts: true,
    meter: true,
    notices: true,
    mypage: true,
    notifications: true,
  },
  sub: {
    dashboard: true,
    complexes: false,
    buildings: false,
    members: false,
    users: false,
    approvals: true,
    "parking.qrs": true,
    "parking.scans": true,
    "meter.cycles": true,
    "meter.submissions": true,
    notices: true,
    settings: false,
    mypage: true,
    notifications: true,
  },
};

export const defaultMenuOrder: MenuOrder = {
  super: [
    "dashboard",
    "complexes",
    "buildings",
    "members",
    "users",
    "approvals",
    "parking.qrs",
    "parking.scans",
    "meter.cycles",
    "meter.submissions",
    "notices",
    "settings",
    "mypage",
    "notifications",
  ],
  main: [
    "dashboard",
    "complexes",
    "buildings",
    "members",
    "users",
    "approvals",
    "parking.qrs",
    "parking.scans",
    "meter.cycles",
    "meter.submissions",
    "notices",
    "settings",
    "mypage",
    "notifications",
  ],
  sub: [
    "dashboard",
    "complexes",
    "buildings",
    "members",
    "users",
    "approvals",
    "parking.qrs",
    "parking.scans",
    "meter.cycles",
    "meter.submissions",
    "notices",
    "settings",
    "mypage",
    "notifications",
  ],
  guard: ["scan", "history", "notices", "mypage", "notifications"],
  resident: ["scan", "myQr", "alerts", "meter", "notices", "mypage", "notifications"],
};

export const defaultMenuLabels: MenuLabels = {
  super: {
    dashboard: "대시보드",
    complexes: "단지 관리",
    buildings: "동 관리",
    members: "회원관리",
    users: "사용자 초대",
    approvals: "승인",
    "parking.qrs": "주차 QR",
    "parking.scans": "경비 스캔 리스트(log)",
    "meter.cycles": "검침 주기",
    "meter.submissions": "검침 제출",
    notices: "공지",
    settings: "설정",
    mypage: "마이페이지",
    notifications: "알림",
  },
  main: {
    dashboard: "대시보드",
    complexes: "단지 관리",
    buildings: "동 관리",
    members: "회원관리",
    users: "사용자 초대",
    approvals: "승인",
    "parking.qrs": "주차 QR",
    "parking.scans": "경비 스캔 리스트(log)",
    "meter.cycles": "검침 주기",
    "meter.submissions": "검침 제출",
    notices: "공지",
    settings: "설정",
    mypage: "마이페이지",
    notifications: "알림",
  },
  sub: {
    dashboard: "대시보드",
    complexes: "단지 관리",
    buildings: "동 관리",
    members: "회원관리",
    users: "사용자 초대",
    approvals: "승인",
    "parking.qrs": "주차 QR",
    "parking.scans": "경비 스캔 리스트(log)",
    "meter.cycles": "검침 주기",
    "meter.submissions": "검침 제출",
    notices: "공지",
    settings: "설정",
    mypage: "마이페이지",
    notifications: "알림",
  },
  guard: {
    scan: "QR 스캔",
    history: "스캔 이력",
    notices: "공지",
    mypage: "마이페이지",
    notifications: "알림",
  },
  resident: {
    scan: "QR 스캔",
    myQr: "내 QR",
    alerts: "알림 내역",
    meter: "검침",
    notices: "공지",
    mypage: "마이페이지",
    notifications: "알림 내역",
  },
};
