import type { MenuToggles } from "./types";

export const defaultMenuToggles: MenuToggles = {
  main: {
    dashboard: true,
    complexes: true,
    buildings: true,
    members: true,
    users: true,
    approvals: true,
    "parking.qrs": true,
    "parking.scans": true,
    "meter.cycles": true,
    "meter.submissions": true,
    notices: true,
    settings: true,
    mypage: true,
    notifications: true,
  },
  guard: {
    scan: true,
    history: true,
    notices: true,
    mypage: true,
    notifications: false,
  },
  resident: {
    scan: true,
    myQr: true,
    alerts: true,
    meter: true,
    notices: true,
    mypage: true,
    notifications: true,
  },
  sub: {
    dashboard: true,
    complexes: false,
    buildings: false,
    members: false,
    users: false,
    approvals: true,
    "parking.qrs": true,
    "parking.scans": true,
    "meter.cycles": true,
    "meter.submissions": true,
    notices: true,
    settings: false,
    mypage: true,
    notifications: true,
  },
};
